# Global settings
replicaCount: 1
image:
  repository: your-registry/flask-app
  tag: latest
  pullPolicy: IfNotPresent

# Service
service:
  type: ClusterIP
  port: 5000

# Resources
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi


# Environment variables
env:
  FLASK_ENV: production
  